
// -- user code here --

/* --- start generated code --- */

// Generated by  1.4.4 (Phaser v2.6.2)


/**
 * dinoDeath.
 * @param {Phaser.Game} aGame A reference to the currently running game.
 * @param {Phaser.Group} aParent The parent Group (or other {@link DisplayObject}) that this group will be added to.
    If undefined/unspecified the Group will be added to the {@link Phaser.Game#world Game World}; if null the Group will not be added to any parent.
 * @param {string} aName A name for this group. Not used internally but useful for debugging.
 * @param {boolean} aAddToStage If true this group will be added directly to the Game.Stage instead of Game.World.
 * @param {boolean} aEnableBody If true all Sprites created with {@link #create} or {@link #createMulitple} will have a physics body created on them. Change the body type with {@link #physicsBodyType}.
 * @param {number} aPhysicsBodyType The physics body type to use when physics bodies are automatically added. See {@link #physicsBodyType} for values.
 */
function DinoDeath(aGame, aParent, aName, aAddToStage, aEnableBody, aPhysicsBodyType) {
	
	Phaser.Group.call(this, aGame, aParent, aName, aAddToStage, aEnableBody, aPhysicsBodyType);
	var _x_icon = this.game.add.sprite(0, 0, 'commandFail', 0, this);
	_x_icon.anchor.setTo(0.5, 0.5);
	_x_icon.animations.add('death', [0, 1, 2, 3, 4, 5, 6], 20, false);
	
	var _ghost = this.game.add.sprite(22, -80, 'dinoDeath', 0, this);
	_ghost.anchor.setTo(0.5, 0.5);
	_ghost.animations.add('ghost', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 20, false);
	
	
	
	// public fields
	
	this.fX_icon = _x_icon;
	this.fGhost = _ghost;
	
	/* --- post-init-begin --- */
	var animGhost = this.fGhost.animations.getAnimation("ghost");
	animGhost.onComplete.add(function() {
		
		var curState = this.game.state.getCurrentState();
		var endTween = this.game.add.tween(curState.fInGameGroup.scale);
		var endGhostTween = this.game.add.tween(this.scale);
		
		endTween.to({x:DinoRunz.GameConfig.end_scale, y:DinoRunz.GameConfig.end_scale}, 500, Phaser.Easing.Linear.None, true);
		endTween.onUpdateCallback(function(inParam) {
		    curState.path.setDeadViewScale(inParam.target.x);
		}, this);
		
		endGhostTween.to({x:DinoRunz.GameConfig.end_scale, y:DinoRunz.GameConfig.end_scale}, 500, Phaser.Easing.Linear.None, true);
		endGhostTween.onComplete.addOnce(function() {
			this.game.state.getCurrentState().menuScene.openMenu(curState.currentStage, MenuScene.EMenuType.RESTART);
			this.hideDeathEffect();	
		}, this);
	}, this);
	
	this.visible = false;
	/* --- post-init-end --- */
}

/** @type Phaser.Group */
var dinoDeath_proto = Object.create(Phaser.Group.prototype);
DinoDeath.prototype = dinoDeath_proto;
DinoDeath.prototype.constructor = DinoDeath;

/* --- end generated code --- */
// -- user code here --
DinoDeath.prototype.showDeathEffect = function() {
	this.scale.setTo(1);
	this.visible = true;
	this.fX_icon.animations.play("death", 25);
	this.fGhost.animations.play("ghost", 25);
};

DinoDeath.prototype.hideDeathEffect = function() {
	this.visible = false;
};