
// -- user code here --

/* --- start generated code --- */

// Generated by  1.4.4 (Phaser v2.6.2)


/**
 * EndingCover.
 * @param {Phaser.Game} aGame A reference to the currently running game.
 * @param {Phaser.Group} aParent The parent Group (or other {@link DisplayObject}) that this group will be added to.    If undefined/unspecified the Group will be added to the {@link Phaser.Game#world Game World}; if null the Group will not be added to any parent.
 * @param {string} aName A name for this group. Not used internally but useful for debugging.
 * @param {boolean} aAddToStage If true this group will be added directly to the Game.Stage instead of Game.World.
 * @param {boolean} aEnableBody If true all Sprites created with {@link #create} or {@link #createMulitple} will have a physics body created on them. Change the body type with {@link #physicsBodyType}.
 * @param {number} aPhysicsBodyType The physics body type to use when physics bodies are automatically added. See {@link #physicsBodyType} for values.
 */
function EndingCover(aGame, aParent, aName, aAddToStage, aEnableBody, aPhysicsBodyType) {
	
	Phaser.Group.call(this, aGame, aParent, aName, aAddToStage, aEnableBody, aPhysicsBodyType);
	this.game.add.sprite(146, 346, 'allClearAtlas', 'particle.png', this);
	
	var _particle_png1 = this.game.add.sprite(443, 218, 'allClearAtlas', 'particle.png', this);
	_particle_png1.scale.setTo(1.5, 1.5);
	
	this.game.add.sprite(215, 151, 'allClearAtlas', 'particle.png', this);
	
	var _particle_png3 = this.game.add.sprite(132, 44, 'allClearAtlas', 'particle.png', this);
	_particle_png3.scale.setTo(1.5, 1.5);
	
	this.game.add.sprite(561, 155, 'allClearAtlas', 'particle.png', this);
	
	var _particle_png5 = this.game.add.sprite(433, 96, 'allClearAtlas', 'particle.png', this);
	_particle_png5.scale.setTo(0.8, 0.8);
	
	this.game.add.sprite(629, 74, 'allClearAtlas', 'particle.png', this);
	
	var _particle_png7 = this.game.add.sprite(542, 305, 'allClearAtlas', 'particle.png', this);
	_particle_png7.scale.setTo(0.8, 0.8);
	
	this.game.add.sprite(652, 346, 'allClearAtlas', 'particle.png', this);
	
	this.game.add.sprite(43, 259, 'allClearAtlas', 'particle.png', this);
	
	var _particle_png10 = this.game.add.sprite(84, 155, 'allClearAtlas', 'particle.png', this);
	_particle_png10.scale.setTo(0.8, 0.8);
	
	
	
}

/** @type Phaser.Group */
var EndingCover_proto = Object.create(Phaser.Group.prototype);
EndingCover.prototype = EndingCover_proto;
EndingCover.prototype.constructor = EndingCover;

/* --- end generated code --- */
// -- user code here --
