
// -- user code here --

/* --- start generated code --- */

// Generated by  1.4.4 (Phaser v2.6.2)


/**
 * GetNewCharacterEffect.
 * @param {Phaser.Game} aGame A reference to the currently running game.
 * @param {Phaser.Group} aParent The parent Group (or other {@link DisplayObject}) that this group will be added to.
    If undefined/unspecified the Group will be added to the {@link Phaser.Game#world Game World}; if null the Group will not be added to any parent.
 * @param {string} aName A name for this group. Not used internally but useful for debugging.
 * @param {boolean} aAddToStage If true this group will be added directly to the Game.Stage instead of Game.World.
 * @param {boolean} aEnableBody If true all Sprites created with {@link #create} or {@link #createMulitple} will have a physics body created on them. Change the body type with {@link #physicsBodyType}.
 * @param {number} aPhysicsBodyType The physics body type to use when physics bodies are automatically added. See {@link #physicsBodyType} for values.
 */
function GetNewCharacterEffect(aGame, aParent, aName, aAddToStage, aEnableBody, aPhysicsBodyType) {
	
	Phaser.Group.call(this, aGame, aParent, aName, aAddToStage, aEnableBody, aPhysicsBodyType);
	var _getCharBG_png = this.game.add.sprite(0, 0, 'MenuScene', 'getCharBG.png', this);
	_getCharBG_png.anchor.setTo(0.5, 0.5);
	
	var _sprLightning = this.game.add.sprite(-175, -21, 'MenuScene', 'getCharlighting.png', this);
	_sprLightning.anchor.setTo(0.5, 0.5);
	
	var _sprCharacter = this.game.add.sprite(-175, -21, 'auhaSheet1', 8, this);
	_sprCharacter.anchor.setTo(0.5, 0.5);
	
	var _text = this.game.add.text(54, -24, 'GET A NEW CHARACTER!', {"font":"bold 28px Blogger Sans","fill":"#1a8aa8"}, this);
	_text.anchor.setTo(0.5, 0.5);
	
	
	
	// public fields
	
	this.fSprLightning = _sprLightning;
	this.fSprCharacter = _sprCharacter;
	/* --- post-init-begin --- */
	this.tween = null;
	
	var rotateTween = this.game.add.tween(this.fSprLightning);
	rotateTween.to({angle:360}, 2000, Phaser.Easing.Linear.None, true, 0, -1, false);
	/* --- post-init-end --- */
	
	
}

/** @type Phaser.Group */
var GetNewCharacterEffect_proto = Object.create(Phaser.Group.prototype);
GetNewCharacterEffect.prototype = GetNewCharacterEffect_proto;
GetNewCharacterEffect.prototype.constructor = GetNewCharacterEffect;

/* --- end generated code --- */
// -- user code here --
GetNewCharacterEffect.prototype.showGetNewCharacter = function(charId) {
	this.fSprCharacter.loadTexture("auhaSheet"+charId, 8, false);

	this.position.y = -100;
	this.tween = this.game.add.tween(this.position);
	this.tween.to({y:71}, 300, Phaser.Easing.Linear.None, true);
	this.tween.onComplete.addOnce(function() {
		this.game.tweens.remove(this.tween);
	}, this);

	this.visible = true;

	setTimeout(this.hideEffect.bind(this), 1800);
}

GetNewCharacterEffect.prototype.hideEffect = function() {
	this.tween = this.game.add.tween(this.position);
	this.tween.to({y:-100}, 300, Phaser.Easing.Linear.None, true);
	this.tween.onComplete.addOnce(function() {
		this.game.tweens.remove(this.tween);
		this.visible = false;
	}, this);
}