
// -- user code here --

/* --- start generated code --- */

// Generated by  1.4.4 (Phaser v2.6.2)


/**
 * TitleUserProfile.
 * @param {Phaser.Game} aGame A reference to the currently running game.
 * @param {Phaser.Group} aParent The parent Group (or other {@link DisplayObject}) that this group will be added to.    If undefined/unspecified the Group will be added to the {@link Phaser.Game#world Game World}; if null the Group will not be added to any parent.
 * @param {string} aName A name for this group. Not used internally but useful for debugging.
 * @param {boolean} aAddToStage If true this group will be added directly to the Game.Stage instead of Game.World.
 * @param {boolean} aEnableBody If true all Sprites created with {@link #create} or {@link #createMulitple} will have a physics body created on them. Change the body type with {@link #physicsBodyType}.
 * @param {number} aPhysicsBodyType The physics body type to use when physics bodies are automatically added. See {@link #physicsBodyType} for values.
 */
function TitleUserProfile(aGame, aParent, aName, aAddToStage, aEnableBody, aPhysicsBodyType) {
	
	Phaser.Group.call(this, aGame, aParent, aName, aAddToStage, aEnableBody, aPhysicsBodyType);
	var _sprUserProfile = this.game.add.sprite(0, 0, 'titleAtlas', 'img_titleUserFaceArea.png', this);
	_sprUserProfile.anchor.setTo(0.5, 0.5);
	
	var _img_titleFrame_png = this.game.add.sprite(0, 0, 'titleAtlas', 'img_titleFrame.png', this);
	_img_titleFrame_png.anchor.setTo(0.5, 0.5);
	
	this.game.add.sprite(51, -1, 'titleAtlas', 'img_world001.png', this);
	
	var _userBestStage = this.game.add.text(98, 21, '9999', {"font":"bold 24px Arial","fill":"#8991e4"}, this);
	_userBestStage.anchor.setTo(0.0, 0.5);
	
	var _userName = this.game.add.text(51, -27, 'userName', {"font":"bold 28px Arial","fill":"#ff9100"}, this);
	_userName.anchor.setTo(0.0, 0.5);
	
	
	
	// public fields
	
	this.fSprUserProfile = _sprUserProfile;
	this.fUserBestStage = _userBestStage;
	this.fUserName = _userName;
	/* --- post-init-begin --- */
	var profileMask = this.game.add.graphics(0, 0, this);
	profileMask.beginFill(0xffffff);
	profileMask.drawCircle(0, 0, this.fSprUserProfile.width);
	profileMask.endFill();
	profileMask.position.setTo(this.fSprUserProfile.position.x, this.fSprUserProfile.position.y);
	
	this.fSprUserProfile.mask = profileMask;
	/* --- post-init-end --- */
	
	
}

/** @type Phaser.Group */
var TitleUserProfile_proto = Object.create(Phaser.Group.prototype);
TitleUserProfile.prototype = TitleUserProfile_proto;
TitleUserProfile.prototype.constructor = TitleUserProfile;

/* --- end generated code --- */
// -- user code here --
TitleUserProfile.prototype.setProfile = function(imageKey, name, stage) {
	this.fSprUserProfile.loadTexture(imageKey);
	
	if(this.fSprUserProfile.width !== 75) {
		this.fSprUserProfile.width = 75;
		this.fSprUserProfile.height = 75;
	}
	
	this.fUserName.text = StzUtil.cutText(name, 7);
	
	this.fUserBestStage.text = stage;
};