
// -- user code here --

/* --- start generated code --- */

// Generated by  1.4.4 (Phaser v2.6.2)


/**
 * ButtonStage.
 * @param {Phaser.Game} aGame A reference to the currently running game.
 * @param {Phaser.Group} aParent The parent Group (or other {@link DisplayObject}) that this group will be added to.
    If undefined/unspecified the Group will be added to the {@link Phaser.Game#world Game World}; if null the Group will not be added to any parent.
 * @param {string} aName A name for this group. Not used internally but useful for debugging.
 * @param {boolean} aAddToStage If true this group will be added directly to the Game.Stage instead of Game.World.
 * @param {boolean} aEnableBody If true all Sprites created with {@link #create} or {@link #createMulitple} will have a physics body created on them. Change the body type with {@link #physicsBodyType}.
 * @param {number} aPhysicsBodyType The physics body type to use when physics bodies are automatically added. See {@link #physicsBodyType} for values.
 */
function ButtonStage(aGame, aParent, aName, aAddToStage, aEnableBody, aPhysicsBodyType) {
	
	Phaser.Group.call(this, aGame, aParent, aName, aAddToStage, aEnableBody, aPhysicsBodyType);
	var _groupOpen = this.game.add.group(this);
	
	var _btnStage = this.game.add.sprite(0, 0, 'MenuScene', 'img_stage_01Stage.png', _groupOpen);
	_btnStage.scale.setTo(2.0, 2.0);
	_btnStage.anchor.setTo(0.5, 0.5);
	
	var _sprAllClear = this.game.add.sprite(0, -37, 'MenuScene', 'img_crown01Disable.png', _groupOpen);
	_sprAllClear.scale.setTo(2.0, 2.0);
	_sprAllClear.anchor.setTo(0.5, 0.5);
	
	var _txtStage = this.game.add.text(0, 8, '1', {"font":"bold 56px Blogger Sans","align":"center"}, _groupOpen);
	_txtStage.anchor.setTo(0.5, 0.5);
	
	var _groupUserPhoto = this.game.add.group(_groupOpen);
	_groupUserPhoto.position.setTo(2, -79);
	
	var _sprCurrentStageBG = this.game.add.sprite(0, 0, 'MenuScene', 'img_userCurrentStageBG.png', _groupUserPhoto);
	_sprCurrentStageBG.scale.setTo(2.0, 2.0);
	_sprCurrentStageBG.anchor.setTo(0.5, 0.5);
	
	var _sprUserPhoto = this.game.add.sprite(0, -8, 'MenuScene', 'default_thumb.png', _groupUserPhoto);
	_sprUserPhoto.scale.setTo(2.0, 2.0);
	_sprUserPhoto.anchor.setTo(0.5, 0.5);
	
	var _groupLock = this.game.add.group(this);
	
	var _btnLockStage = this.game.add.sprite(0, -5, 'MenuScene', 'img_stage_03.png', _groupLock);
	_btnLockStage.scale.setTo(2.0, 2.0);
	_btnLockStage.anchor.setTo(0.5, 0.5);
	
	var _txtLockStage = this.game.add.text(0, 7, '99', {"font":"bold 36px Blogger Sans"}, _groupLock);
	_txtLockStage.anchor.setTo(0.5, 0.5);
	
	
	
	// public fields
	
	this.fGroupOpen = _groupOpen;
	this.fBtnStage = _btnStage;
	this.fSprAllClear = _sprAllClear;
	this.fTxtStage = _txtStage;
	this.fGroupUserPhoto = _groupUserPhoto;
	this.fSprCurrentStageBG = _sprCurrentStageBG;
	this.fSprUserPhoto = _sprUserPhoto;
	this.fGroupLock = _groupLock;
	this.fBtnLockStage = _btnLockStage;
	this.fTxtLockStage = _txtLockStage;
	/* --- post-init-begin --- */
	var maskUserPhoto = this.game.add.graphics(0, 0);
	maskUserPhoto.beginFill(0xffffff);
	maskUserPhoto.drawCircle(this.fSprUserPhoto.position.x, this.fSprUserPhoto.position.y, this.fSprUserPhoto.width);
	this.fGroupUserPhoto.addChild(maskUserPhoto);
	this.fSprUserPhoto.mask = maskUserPhoto;
	
	this.stage = 1;
	this.fBtnStage.inputEnabled = true;
	this.fBtnStage.events.onInputUp.add(function() {
		window.sounds.sound('sfx_button').play();
		this.game.state.getCurrentState().newGame(this.stage);
	}, this);
	/* --- post-init-end --- */
	
	
}

/** @type Phaser.Group */
var ButtonStage_proto = Object.create(Phaser.Group.prototype);
ButtonStage.prototype = ButtonStage_proto;
ButtonStage.prototype.constructor = ButtonStage;

/* --- end generated code --- */
// -- user code here --

ButtonStage.prototype.setStage = function(inStage) {
	this.stage = inStage;
	
	var textureKey = (DinoRunz.Storage.isAllClear()) ? "img_crown01Disable.png" : "img_crown02Clear.png";
	this.fSprAllClear.loadTexture("MenuScene", textureKey);
	
	var userLastClearedStage = DinoRunz.Storage.UserData.lastClearedStage;
	
	// all clear setting
	this.setAllClear(DinoRunz.Storage.getAllClearValue(this.stage));
	
	if(this.stage<userLastClearedStage) {
		this.fGroupOpen.visible = true;
		this.fGroupLock.visible = false;
		this.fGroupUserPhoto.visible = false;
		
		this.fTxtStage.text = inStage + "";
		this.fTxtStage.fill = "#00add2";
		this.fTxtStage.fontSize = (inStage<100) ? "56px":"45px";
		
		this.fBtnStage.loadTexture("MenuScene", "img_stage_01Stage.png");
	}
	else if(this.stage>userLastClearedStage) {
		this.fGroupOpen.visible = false;
		this.fGroupLock.visible = true;
		
		this.fTxtLockStage.text = inStage + "";
		this.fTxtLockStage.fill = "#cde9ec";
		this.fTxtLockStage.fontSize = (inStage<100) ? "36px":"30px";
	}
	else {
		this.fGroupOpen.visible = true;
		this.fGroupLock.visible = false;
		this.fGroupUserPhoto.visible = true;
		
		this.fTxtStage.text = inStage + "";
		this.fTxtStage.fill = "#ffffff";
		this.fTxtStage.fontSize = (inStage<100) ? "56px":"45px";
		
		this.fBtnStage.loadTexture("MenuScene", "img_stage_02currentStage.png");
	}
};

ButtonStage.prototype.setAllClear = function(inValue) {
	switch(inValue){
		case 2:
		this.fSprAllClear.loadTexture("MenuScene", "img_crown02Clear.png");
		break;
		case 1:
		this.fSprAllClear.loadTexture("MenuScene", "img_crown01Disable.png");
		break;
		case 0:
		this.fSprAllClear.loadTexture("MenuScene", "img_crown00none.png");
		break;
	}
	
	this.fSprAllClear.visible = (this.stage<DinoRunz.Storage.UserData.lastClearedStage);
};

ButtonStage.prototype.getWidth = function() {
	return this.fBtnLockStage.width;
};

ButtonStage.prototype.getHeight = function() {
	return this.fBtnLockStage.height;
};

ButtonStage.prototype.setUserPhoto = function(userPhotoKey) {
	this.fSprUserPhoto.loadTexture(userPhotoKey);
	
	if(this.fSprUserPhoto.width>66) {
		this.fSprUserPhoto.width = 66;
		this.fSprUserPhoto.height = 66;
	}
};